### ISSUE TITLE
Python 3.7 support

### ISSUE THREAD

**Issue by Avamander** [vthorsteinsson/Skrafl#8]
When one tries to run `dawgbuilder.py` with Python3.7 (as support was advertised in the README.md file, if that applies to some part of Skafl, it would be really nice to know) the script errors with `cPickle not found` in file `dawgdictionary.py`, reason for that might be that in Python 3.7 the package is named `_pickle` not `cPickle`. 

I'm unfortunately not familiar enough with Python2/3 interop to make a PR with the necessary fix.

**Comment by vthorsteinsson** [comment]
Should be fixed in the newest commit - try pulling the newest version and running `dawgbuilder.py` again. You can then run `dawgtester.py` to check whether everything is OK. Let me know how it goes!
